# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/herrylv/tencentcloud-cls-sdk-c/tencentcloud-cls-sdk-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/herrylv/tencentcloud-cls-sdk-c/tencentcloud-cls-sdk-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/herrylv/tencentcloud-cls-sdk-c/tencentcloud-cls-sdk-c/CMakeFiles /home/herrylv/tencentcloud-cls-sdk-c/tencentcloud-cls-sdk-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/herrylv/tencentcloud-cls-sdk-c/tencentcloud-cls-sdk-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cls_log_csdk

# Build rule for target.
cls_log_csdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cls_log_csdk
.PHONY : cls_log_csdk

# fast build rule for target.
cls_log_csdk/fast:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/build
.PHONY : cls_log_csdk/fast

#=============================================================================
# Target rules for targets named cls_log_csdk_static

# Build rule for target.
cls_log_csdk_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cls_log_csdk_static
.PHONY : cls_log_csdk_static

# fast build rule for target.
cls_log_csdk_static/fast:
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/build
.PHONY : cls_log_csdk_static/fast

#=============================================================================
# Target rules for targets named post_log_demo

# Build rule for target.
post_log_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 post_log_demo
.PHONY : post_log_demo

# fast build rule for target.
post_log_demo/fast:
	$(MAKE) -f demo/CMakeFiles/post_log_demo.dir/build.make demo/CMakeFiles/post_log_demo.dir/build
.PHONY : post_log_demo/fast

# target to build an object file
src/cls_log.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/cls_log.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/cls_log.o
.PHONY : src/cls_log.o

# target to preprocess a source file
src/cls_log.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/cls_log.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/cls_log.i
.PHONY : src/cls_log.i

# target to generate assembly for a file
src/cls_log.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/cls_log.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/cls_log.s
.PHONY : src/cls_log.s

# target to build an object file
src/cls_logs.pb-c.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/cls_logs.pb-c.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/cls_logs.pb-c.o
.PHONY : src/cls_logs.pb-c.o

# target to preprocess a source file
src/cls_logs.pb-c.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/cls_logs.pb-c.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/cls_logs.pb-c.i
.PHONY : src/cls_logs.pb-c.i

# target to generate assembly for a file
src/cls_logs.pb-c.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/cls_logs.pb-c.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/cls_logs.pb-c.s
.PHONY : src/cls_logs.pb-c.s

# target to build an object file
src/log_adaptor.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_adaptor.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_adaptor.o
.PHONY : src/log_adaptor.o

# target to preprocess a source file
src/log_adaptor.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_adaptor.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_adaptor.i
.PHONY : src/log_adaptor.i

# target to generate assembly for a file
src/log_adaptor.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_adaptor.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_adaptor.s
.PHONY : src/log_adaptor.s

# target to build an object file
src/log_cache_queue.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_cache_queue.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_cache_queue.o
.PHONY : src/log_cache_queue.o

# target to preprocess a source file
src/log_cache_queue.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_cache_queue.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_cache_queue.i
.PHONY : src/log_cache_queue.i

# target to generate assembly for a file
src/log_cache_queue.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_cache_queue.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_cache_queue.s
.PHONY : src/log_cache_queue.s

# target to build an object file
src/log_error.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_error.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_error.o
.PHONY : src/log_error.o

# target to preprocess a source file
src/log_error.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_error.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_error.i
.PHONY : src/log_error.i

# target to generate assembly for a file
src/log_error.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_error.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_error.s
.PHONY : src/log_error.s

# target to build an object file
src/log_polymerization.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_polymerization.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_polymerization.o
.PHONY : src/log_polymerization.o

# target to preprocess a source file
src/log_polymerization.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_polymerization.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_polymerization.i
.PHONY : src/log_polymerization.i

# target to generate assembly for a file
src/log_polymerization.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_polymerization.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_polymerization.s
.PHONY : src/log_polymerization.s

# target to build an object file
src/log_producer_client.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_client.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_client.o
.PHONY : src/log_producer_client.o

# target to preprocess a source file
src/log_producer_client.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_client.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_client.i
.PHONY : src/log_producer_client.i

# target to generate assembly for a file
src/log_producer_client.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_client.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_client.s
.PHONY : src/log_producer_client.s

# target to build an object file
src/log_producer_config.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_config.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_config.o
.PHONY : src/log_producer_config.o

# target to preprocess a source file
src/log_producer_config.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_config.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_config.i
.PHONY : src/log_producer_config.i

# target to generate assembly for a file
src/log_producer_config.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_config.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_config.s
.PHONY : src/log_producer_config.s

# target to build an object file
src/log_producer_manager.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_manager.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_manager.o
.PHONY : src/log_producer_manager.o

# target to preprocess a source file
src/log_producer_manager.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_manager.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_manager.i
.PHONY : src/log_producer_manager.i

# target to generate assembly for a file
src/log_producer_manager.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/log_producer_manager.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/log_producer_manager.s
.PHONY : src/log_producer_manager.s

# target to build an object file
src/lz4.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/lz4.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/lz4.o
.PHONY : src/lz4.o

# target to preprocess a source file
src/lz4.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/lz4.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/lz4.i
.PHONY : src/lz4.i

# target to generate assembly for a file
src/lz4.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/lz4.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/lz4.s
.PHONY : src/lz4.s

# target to build an object file
src/map.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/map.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/map.o
.PHONY : src/map.o

# target to preprocess a source file
src/map.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/map.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/map.i
.PHONY : src/map.i

# target to generate assembly for a file
src/map.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/map.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/map.s
.PHONY : src/map.s

# target to build an object file
src/md5.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/md5.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/md5.o
.PHONY : src/md5.o

# target to preprocess a source file
src/md5.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/md5.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/md5.i
.PHONY : src/md5.i

# target to generate assembly for a file
src/md5.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/md5.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/md5.s
.PHONY : src/md5.s

# target to build an object file
src/post_logs_api.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/post_logs_api.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/post_logs_api.o
.PHONY : src/post_logs_api.o

# target to preprocess a source file
src/post_logs_api.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/post_logs_api.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/post_logs_api.i
.PHONY : src/post_logs_api.i

# target to generate assembly for a file
src/post_logs_api.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/post_logs_api.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/post_logs_api.s
.PHONY : src/post_logs_api.s

# target to build an object file
src/post_logs_client.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/post_logs_client.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/post_logs_client.o
.PHONY : src/post_logs_client.o

# target to preprocess a source file
src/post_logs_client.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/post_logs_client.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/post_logs_client.i
.PHONY : src/post_logs_client.i

# target to generate assembly for a file
src/post_logs_client.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/post_logs_client.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/post_logs_client.s
.PHONY : src/post_logs_client.s

# target to build an object file
src/protobuf-c.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/protobuf-c.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/protobuf-c.o
.PHONY : src/protobuf-c.o

# target to preprocess a source file
src/protobuf-c.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/protobuf-c.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/protobuf-c.i
.PHONY : src/protobuf-c.i

# target to generate assembly for a file
src/protobuf-c.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/protobuf-c.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/protobuf-c.s
.PHONY : src/protobuf-c.s

# target to build an object file
src/rbtree.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/rbtree.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/rbtree.o
.PHONY : src/rbtree.o

# target to preprocess a source file
src/rbtree.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/rbtree.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/rbtree.i
.PHONY : src/rbtree.i

# target to generate assembly for a file
src/rbtree.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/rbtree.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/rbtree.s
.PHONY : src/rbtree.s

# target to build an object file
src/sds.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/sds.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/sds.o
.PHONY : src/sds.o

# target to preprocess a source file
src/sds.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/sds.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/sds.i
.PHONY : src/sds.i

# target to generate assembly for a file
src/sds.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/sds.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/sds.s
.PHONY : src/sds.s

# target to build an object file
src/sha1.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/sha1.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/sha1.o
.PHONY : src/sha1.o

# target to preprocess a source file
src/sha1.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/sha1.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/sha1.i
.PHONY : src/sha1.i

# target to generate assembly for a file
src/sha1.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/sha1.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/sha1.s
.PHONY : src/sha1.s

# target to build an object file
src/signature.o:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/signature.o
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/signature.o
.PHONY : src/signature.o

# target to preprocess a source file
src/signature.i:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/signature.i
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/signature.i
.PHONY : src/signature.i

# target to generate assembly for a file
src/signature.s:
	$(MAKE) -f CMakeFiles/cls_log_csdk.dir/build.make CMakeFiles/cls_log_csdk.dir/src/signature.s
	$(MAKE) -f CMakeFiles/cls_log_csdk_static.dir/build.make CMakeFiles/cls_log_csdk_static.dir/src/signature.s
.PHONY : src/signature.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cls_log_csdk"
	@echo "... cls_log_csdk_static"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... post_log_demo"
	@echo "... src/cls_log.o"
	@echo "... src/cls_log.i"
	@echo "... src/cls_log.s"
	@echo "... src/cls_logs.pb-c.o"
	@echo "... src/cls_logs.pb-c.i"
	@echo "... src/cls_logs.pb-c.s"
	@echo "... src/log_adaptor.o"
	@echo "... src/log_adaptor.i"
	@echo "... src/log_adaptor.s"
	@echo "... src/log_cache_queue.o"
	@echo "... src/log_cache_queue.i"
	@echo "... src/log_cache_queue.s"
	@echo "... src/log_error.o"
	@echo "... src/log_error.i"
	@echo "... src/log_error.s"
	@echo "... src/log_polymerization.o"
	@echo "... src/log_polymerization.i"
	@echo "... src/log_polymerization.s"
	@echo "... src/log_producer_client.o"
	@echo "... src/log_producer_client.i"
	@echo "... src/log_producer_client.s"
	@echo "... src/log_producer_config.o"
	@echo "... src/log_producer_config.i"
	@echo "... src/log_producer_config.s"
	@echo "... src/log_producer_manager.o"
	@echo "... src/log_producer_manager.i"
	@echo "... src/log_producer_manager.s"
	@echo "... src/lz4.o"
	@echo "... src/lz4.i"
	@echo "... src/lz4.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/md5.o"
	@echo "... src/md5.i"
	@echo "... src/md5.s"
	@echo "... src/post_logs_api.o"
	@echo "... src/post_logs_api.i"
	@echo "... src/post_logs_api.s"
	@echo "... src/post_logs_client.o"
	@echo "... src/post_logs_client.i"
	@echo "... src/post_logs_client.s"
	@echo "... src/protobuf-c.o"
	@echo "... src/protobuf-c.i"
	@echo "... src/protobuf-c.s"
	@echo "... src/rbtree.o"
	@echo "... src/rbtree.i"
	@echo "... src/rbtree.s"
	@echo "... src/sds.o"
	@echo "... src/sds.i"
	@echo "... src/sds.s"
	@echo "... src/sha1.o"
	@echo "... src/sha1.i"
	@echo "... src/sha1.s"
	@echo "... src/signature.o"
	@echo "... src/signature.i"
	@echo "... src/signature.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

